# Generated by Django 5.0.1 on 2025-05-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaveprice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_prices', to='core.client', verbose_name='العميل'),
        ),
        migrations.AlterUniqueTogether(
            name='leaveprice',
            unique_together={('leave_type', 'duration_days', 'client')},
        ),
    ]
