# Generated by Django 5.0.1 on 2025-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_default_leave_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveprice',
            name='pricing_type',
            field=models.CharField(choices=[('per_day', 'سعر يومي'), ('fixed', 'سعر ثابت للإجازة')], default='per_day', max_length=10, verbose_name='طريقة التسعير'),
        ),
    ]
