# Generated by Django 5.0.1 on 2025-05-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaveprice_pricing_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveprice',
            unique_together={('leave_type', 'duration_days', 'client', 'pricing_type')},
        ),
    ]
