# Generated by Django 5.0.1 on 2025-05-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_leaveprice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/logos/', verbose_name='شعار المستشفى'),
        ),
    ]
