# Generated by Django 5.0.1 on 2025-05-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionleave',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول'),
        ),
        migrations.AlterField(
            model_name='companionleave',
            name='discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول'),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج'),
        ),
    ]
