# Generated by Django 5.0.1 on 2025-05-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_companionleave_admission_date_and_more'),
    ]

    operations = [
        # Skip removing employer field if it doesn't exist
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"
        ),
        migrations.AddField(
            model_name='patient',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جهة العمل'),
        ),
    ]
