# Generated by Django 5.0.1 on 2025-05-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_leave_request'),
        ('core', '0010_leaverequest'),
    ]

    operations = [
    ]
