# Generated by Django 5.0.1 on 2025-05-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_0002_add_leave_request_0010_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
