# Generated by Django 5.0.1 on 2025-05-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250514_0214'),
        ('core', '0012_fix_leaverequest_table'),
    ]

    operations = [
    ]
