# Generated by Django 5.0.1 on 2025-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20250516_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='client',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم العميل (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='admission_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ الدخول (هجري)'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='discharge_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ الخروج (هجري)'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='end_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ النهاية (هجري)'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='issue_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ الإصدار (هجري)'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='prefix',
            field=models.CharField(choices=[('PSL', 'PSL'), ('GSL', 'GSL')], default='PSL', max_length=3, verbose_name='بادئة الإجازة'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='start_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ البداية (هجري)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الطبيب (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنصب (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستشفى (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='employer_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جهة العمل (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المريض (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية (بالإنجليزية)'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='admission_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ الدخول (هجري)'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='discharge_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ الخروج (هجري)'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='end_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ النهاية (هجري)'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='issue_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ الإصدار (هجري)'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='prefix',
            field=models.CharField(choices=[('PSL', 'PSL'), ('GSL', 'GSL')], default='PSL', max_length=3, verbose_name='بادئة الإجازة'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='start_date_hijri',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاريخ البداية (هجري)'),
        ),
    ]
