# Generated by Django 5.0.1 on 2025-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_address_en_client_name_en_client_notes_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionleave',
            name='relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='companionleave',
            name='relation_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة (بالإنجليزية)'),
        ),
    ]
