# Generated by Django 5.0.1 on 2025-05-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_companionleave_relation_companionleave_relation_en'),
    ]

    operations = [
    ]
