# Generated by Django 5.0.1 on 2025-05-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20250519_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.hospital', verbose_name='المستشفى'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهوية'),
        ),
    ]
