# Generated by Django 5.0.1 on 2025-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_patient_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
