# Generated by Django 5.0.1 on 2025-05-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_client_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveprice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='leaveprice',
            constraint=models.UniqueConstraint(condition=models.Q(('pricing_type', 'per_day')), fields=('leave_type', 'duration_days', 'client', 'pricing_type'), name='unique_per_day_price'),
        ),
        migrations.AddConstraint(
            model_name='leaveprice',
            constraint=models.UniqueConstraint(condition=models.Q(('pricing_type', 'fixed')), fields=('leave_type', 'client', 'pricing_type'), name='unique_fixed_price'),
        ),
    ]
