# Generated by Django 5.0.1 on 2025-05-22 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_leaveprice_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='companionleave',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ إنشاء الإجازة'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='core.hospital', verbose_name='المستشفيات'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ إنشاء الإجازة'),
        ),
    ]
