# Generated by Django 5.0.1 on 2025-05-23 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_doctor_hospital_companionleave_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionleave',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ إنشاء الإجازة'),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ إنشاء الإجازة'),
        ),
    ]
