# Generated by Django 5.0.1 on 2025-05-23 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_companionleave_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('setting_type', models.CharField(choices=[('general', 'عام'), ('company', 'الشركة'), ('reports', 'التقارير'), ('notifications', 'الإشعارات'), ('backup', 'النسخ الاحتياطي'), ('security', 'الأمان')], default='general', max_length=20, verbose_name='نوع الإعداد')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['setting_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النسخة')),
                ('backup_type', models.CharField(choices=[('full', 'نسخة كاملة'), ('data', 'البيانات فقط'), ('files', 'الملفات فقط'), ('settings', 'الإعدادات فقط')], max_length=20, verbose_name='نوع النسخة')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('running', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('failed', 'فشلت'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منشئ النسخة')),
            ],
            options={
                'verbose_name': 'سجل النسخة الاحتياطية',
                'verbose_name_plural': 'سجلات النسخ الاحتياطي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجدولة')),
                ('backup_type', models.CharField(choices=[('full', 'نسخة كاملة'), ('data', 'البيانات فقط'), ('files', 'الملفات فقط'), ('settings', 'الإعدادات فقط')], max_length=20, verbose_name='نوع النسخة')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('custom', 'مخصص')], max_length=20, verbose_name='التكرار')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True, verbose_name='يوم الأسبوع (0=الاثنين)')),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='يوم الشهر')),
                ('keep_count', models.PositiveIntegerField(default=7, verbose_name='عدد النسخ المحفوظة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل التالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
            ],
            options={
                'verbose_name': 'جدولة النسخ الاحتياطي',
                'verbose_name_plural': 'جدولة النسخ الاحتياطي',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('auto', 'تلقائي')], default='light', max_length=10, verbose_name='المظهر')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة')),
                ('items_per_page', models.PositiveIntegerField(default=25, verbose_name='عدد العناصر في الصفحة')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='إشعارات الرسائل النصية')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='المصادقة الثنائية')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='آخر تغيير كلمة مرور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
