# Generated by Django 5.0.1 on 2025-05-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_systemsettings_backuprecord_backupschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionleave',
            name='duration_days2',
            field=models.IntegerField(default=1, verbose_name='المدة بالأيام'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='duration_days2',
            field=models.IntegerField(default=1, verbose_name='المدة بالأيام'),
        ),
    ]
